INHERIT: ../mkdocs.yml

site_url: https://Xiaokang2022.github.io/tkintertools/en/ # 站点链接
edit_uri: edit/docs/en/docs # 编辑地址
site_description: Official website of tkintertools # 站点描述
copyright: <a href="#__consent">Change Cookie Settings</a><br/>Copyright &copy; 2022 Xiaokang2022 # 版权信息和 Cookie 设置
docs_dir: docs # 文档目录（默认值）
site_dir: ../site/en/ # 网站目录（默认值）

markdown_extensions:
  ###### Python Markdown 配置（markdown 基础语法）

  # 被 pymdownx.extra 完全替代且【冲突】
  # - abbr # 定义缩写
  # - attr_list # Markdown 元素可添加 HTML 和 CSS 属性
  # - def_list # 定义列表
  # - footnotes # 脚注
  # - md_in_html # Markdown 元素可内嵌在 HTML 中
  # - tables # 表格

  # - fenced_code # 代码块，被 pymdownx.superfences 完全替代且【冲突】
  # - codehilite # 代码高亮，被 pymdownx.highlight 完全替代且优化

  # - nl2br # 换行符会直接换行

  - admonition # 提示框
  - meta # 元数据
  - sane_lists # 理智列表，避免原版 Markdown 列表错误渲染
  - smarty # 优化部分字符串为特殊符号
  - wikilinks # 快捷链接

  - toc: # 目录
      marker: "" # 目录替换文本，空字符串则不替换，缺省为 [TOC]
      title: Contents # 目录标题，material 主题会自动根据语言计算
      anchorlink: false # 锚点链接（默认值），给标题自身锚定链接
      permalink: "&para;" # 锚点符号
      permalink_title: "Permanent Link" # 锚点链接提示词，空字符表示没有
      permalink_leading: false # 前置锚点链接（默认值），将锚点放到标题前面
      baselevel: 1 # 最高级别（默认值），往下顺延
      separator: "-" # 分隔符（默认值），替换空格字符
      toc_depth: 4 # 目录显示级别
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # 锚点链接 URL 格式（小写）
        kwds:
          case: lower

  ###### PyMdown Extensions 配置（markdown 扩展语法）

  # - pymdownx.pathconverter # 相对链接转绝对链接【?】
  # - pymdownx.b64 # 允许使用 base64 编码【?】

  # - pymdownx.striphtml # 去除 HTML 中不需要的注释和 / 或标记属性，被插件 minify 替代
  # - pymdownx.progressbar # 进度条（暂不支持）

  - pymdownx.extra # 见上面 Python Markdown 配置说明

  - pymdownx.blocks.tab # 支持更高级的标签块写法（可能与 pymdownx.tabbed 混淆）
  - pymdownx.blocks.html # 支持一些更高级的 Markdown 内嵌 HTML 语法（pymdownx.blocks 默认开启）
  - pymdownx.blocks.details # 支持更高级的提示框布局（可能与 pymdownx.details 混淆）
  - pymdownx.blocks.definition # 支持更高级的定义块语法（可能与 def_list 混淆）
  - pymdownx.blocks.admonition # 支持更高级提示框语法（可能与 admonition 混淆）

  - pymdownx.saneheaders # 理智标题，“#”和标题间必须有空格
  - pymdownx.smartsymbols # 智能符号优化，比上面的 smarty 支持更多
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.keys # 按键高亮优化，增加图标
  - pymdownx.details # 支持提示框的折叠
  - pymdownx.mark # 文本高亮
  - pymdownx.caret # 文本下划线及上标
  - pymdownx.tilde # 文本删除线及下标
  - pymdownx.betterem # 斜体与粗体优化，更好的嵌套使用

  - pymdownx.arithmatex: # 数学表达式
      generic: true

  - pymdownx.snippets: # 外部片段插入
      url_download: true # 远程文件下载
      url_timeout: 10.0 # 超时时长（默认值）
      url_max_size: 33554432 # 文件大小限制（默认值），32MiB

  - pymdownx.escapeall: # 转义一切
      hardbreak: true # 转义换行符会变成间断 <br>
      nbsp: true # 空格转义会变成无间隔空格 &nbsp;

  - pymdownx.magiclink: # 魔术链接，自动识别链接
      user: "" # 可缺省的用户名（默认值）
      repo: "" # 可缺省的仓库名（默认值）
      hide_protocol: false # 隐藏链接协议头（默认值）
      repo_url_shorthand: true # 识别仓库提交等链接
      repo_url_shortener: true # 仓库提交等链接简短显示
      social_url_shorthand: true # 识别社交账号等链接
      social_url_shortener: true # 社交账号等链接简短显示
      normalize_issue_symbols: true # 规范化 Issue、PR 等链接的表示为 #

  - pymdownx.critic: # 文本评论
      mode: view # view 显示差异，accept 显示修改后，reject 显示修改前

  - pymdownx.tasklist: # 任务列表
      custom_checkbox: true # 允许修改复选框样式（默认已修改）
      clickable_checkbox: true # 允许点击复选框

  - pymdownx.highlight: # 代码高亮
      use_pygments: true # 使用 Pygments 而不是 JavaScript 来渲染高亮
      linenums: true # 显示行号（默认值）
      linenums_style: table # 行号样式 pymdownx-inline 或者 inline 和 table
      anchor_linenums: true # 用锚链接包装代码行号，便于超链接和共享（就是行号可以像锚点一样被点击）
      line_spans: __span # 这对于高亮功能正常工作至关重要
      pygments_lang_class: true # 对于自定义注释标记的运行至关重要
      # auto_title: true # 自动为所有代码块添加一个标题

  - pymdownx.emoji: # Emoji 表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences: # 各种嵌套
      disable_indented_code_blocks: false # 禁用缩进代码块（默认值）
      preserve_tabs: true # 嵌套块格式化表格（实验性）
      custom_fences:
        - name: mermaid # 允许 mermaid 图表语法
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed: # 选项卡
      alternate_style: true # 实验性样式
      combine_header_slug: true # 选项卡 URL 带上父标题的前缀
      separator: "-" # 分隔符（默认值），替换空格字符
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}

theme: # 此项各个设定因主题而异
  custom_dir: ../docs/overrides # 覆盖目录
  language: en # 主题语言
  palette:
    - media: "(prefers-color-scheme)" # 系统主题
      toggle:
        icon: material/theme-light-dark
        name: System Mode
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Dark Mode

extra: # 额外设定
  alternate:
    - name: 简体中文
      link: ../
      lang: zh
    - name: English
      link: /
      lang: en
  status: # 元信息状态标识
    new: Recently added
    deprecated: Will be removed soon
  social: # 社交联系方式（页面右下角内容）
    - icon: fontawesome/brands/github
      link: https://github.com/Xiaokang2022/tkintertools/
      name: GitHub Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tkintertools/
      name: PyPI
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/498105668
      name: Bilibili
    - icon: fontawesome/solid/paper-plane
      link: mailto:2951256653@qq.com
      name: Contact the author
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics: # 谷歌统计
    provider: google
    property: G-9YC5SN4ZFD
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-neutral-outline
          name: Just so-so
          data: 0
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Could be improved
          data: -1
          note: Thanks for your feedback!

extra_javascript:
  - ../docs/extra/javascript/shortcuts.js # 绑定左右键换页的键盘快捷键
  - ../docs/extra/javascript/mouse.js # 鼠标点击烟花效果
  - ../docs/extra/javascript/typing-en.js # 打字机效果
  # - ../docs/extra/javascript/canvas-nest.js # 背景效果
  - ../docs/extra/javascript/time.js # 网站运行时间
  - ../docs/extra/javascript/mathjax.js # 数学表达式
  - ../docs/extra/javascript/tablesort.js # 表格排序功能
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # 数学表达式运行环境
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # 表格排序功能运行环境（默认文本类型）
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.date.min.js # 表格排序功能（日期类型）
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.dotsep.min.js # 表格排序功能（点分割类型）
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.filesize.min.js # 表格排序功能（文件大小类型）
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.monthname.min.js # 表格排序功能（月份名称类型）
  - https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.number.min.js # 表格排序功能（数字类型）

extra_css:
  - ../docs/extra/css/extra.css # 加载自定义的样式
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css # 设置字体（霞鹜文楷）

nav:
  - Home:
      - Homepage: index.md
      - License: LICENSE.md
      - Changelog: CHANGELOG.md
      - Todo: TODO.md
      - Contribution Guide: CONTRIBUTING.md
      - Security Policy: SECURITY.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Sponsor this Project: Sponsor.md

  - Tutorials & Documents: https://xiaokang2022.github.io/tkintertools-docs/

  - Projects:
      - Overview: projects/index.md
      - Official Projects:
          - 1. Intelligent Magic Cube: projects/official/1.md
          - 2. Chinese Chess: projects/official/2.md
          - 3. Super Gobang: projects/official/3.md
          - 4. Todo List: projects/official/4.md
      - Users Projects:
          - 1. Login2.0: projects/users/1.md

  - Videos:
      - Overview: videos/index.md
      - 干掉 tkinter！tkintertools 大更新啦！: videos/pages/4.md
      - tkintertools 又更新啦！: videos/pages/3.md
      - 碾压 tkinter 的 UI 框架：tkintertools 3.0.0 正式进入 beta 公测阶段: videos/pages/2.md
      - 这还是你记忆中的 tkinter 的程序吗？？？: videos/pages/1.md
