site_name: tkintertools # 站点名称
site_url: https://Xiaokang2022.github.io/tkintertools/ # 站点链接
repo_url: https://github.com/Xiaokang2022/tkintertools # 仓库地址
repo_name: Xiaokang2022/tkintertools # 仓库名称
edit_uri: edit/docs/docs # 编辑地址（页面会出现编辑按钮）
site_description: Official website of tkintertools # 站点描述
site_author: Xiaokang2022 # 站点作者
remote_branch: gh-pages # GitHub Pages 分支名称（此处为默认值）
remote_name: origin # 远程分支的名称（默认值）
docs_dir: docs # 文档目录（默认值）
site_dir: site # 网站目录（默认值）
dev_addr: 127.0.0.1:8000 # 开发模式下的 IP 地址（默认值）
copyright: Copyright &copy; 2022 Xiaokang2022

markdown_extensions:
  ###### Python Markdown 配置（markdown 基础语法）

  # 被 Pymdownx.superfences 完全替代【冲突】
  # - fenced_code

  # 被 Pymdownx.extra 完全替代【冲突】
  # - abbr # 文本悬浮提示
  # - attr_list # 允许给 md 元素增加 HTML 和 CSS 属性，如一个按钮 [Subscribe to our mailing list](#){: .md-button }，甚至图标，详细见 https://mkdoc-material.llango.com/reference/buttons/
  # - def_list # 允许“定义列表”的语法
  # - footnotes # 脚注
  # - md_in_html # md 内嵌在 HTML 中
  # - tables # 表格

  - admonition # 允许各种各样的提示框，或代码框
  # - codehilite # 被 pymdownx 相关扩展取代了，不建议使用这个
  - meta # 允许元标记，页面源代码顶上那几行被横线保住的内容就是元标记，为了支持某些功能使用
  # - nl2br # 换行符硬断裂，即文本不像旧版 md 那样，可以直接换行
  - sane_lists # 理智列表，避免旧版 md 抽风（强烈推荐开启）
  - smarty # 貌似是为了提高兼容性的，不太清楚
  - wikilinks # 支持快捷链接语法，例如 [[a link]]，会变成 ./a_link/

  - toc: # 目录设置
      title: 目录 # 在右侧导航侧边栏中设置目录的标题
      permalink_title: 点击定位到锚点 # 设置锚点链接的提示词
      permalink: "#" # 启用目录锚点，并设置符号为 “#”
      toc_depth: 3
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # 这啥玩意儿，不懂，抄官网的
        kwds:
          case: lower

  ###### PyMdown Extensions 配置（markdown 扩展语法）

  - pymdownx.extra # 见上面说明

  - pymdownx.striphtml # 去除 HTML 中不需要的注释和 / 或标记属性，可减小 HTML 大小

  - pymdownx.b64 # 允许使用 base64 编码嵌入本地 PNG、JPEG 和 GIF 图像引用（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.escapeall # 允许使用反斜杠（pymdownx 支持，mkdocs 貌似部分支持，不完全支持）
  - pymdownx.magiclink # 自动识别超链接（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.progressbar # 允许进度条语法（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.saneheaders # “#title” 也是标题，虽然中间没有空格（pymdownx 支持，mkdocs 暂时不支持）

  - pymdownx.blocks.tab # 支持更高级的标签块写法（危：可能与 pymdownx.tabbed 冲突）
  - pymdownx.blocks.html # 支持一些更高级的 md 内嵌 HTML 语法（pymdownx.blocks 默认开启）
  - pymdownx.blocks.details # 支持更高级的提示框布局（危：可能与 pymdownx.details 冲突）
  - pymdownx.blocks.admonition # 支持更高级提示框语法（危：可能与 admonition 冲突）
  - pymdownx.blocks.definition # 支持更高级的定义块语法（危：可能与 def_list）

  # 外部片段插入
  # 单行：--8<-- "filename.ext"
  # 多行：类似代码块，允许插入多个文件，每行一个，无需引号
  # 暂时隐藏片段：; filename.ext
  # 指定行（可缺省）：filename.ext:start:end
  - pymdownx.snippets

  # 智能符号优化，支持更多
  # 举例：(c) 就是 ©️
  - pymdownx.smartsymbols

  # 行内代码高亮
  # 格式一：`#!lang code`
  # 格式二：`:::lang code`
  - pymdownx.inlinehilite

  # 按键高亮优化，增加图标
  # 格式（key 要小写）：++key++
  # 连写格式：++key1+key2++
  # 特殊内容：++"My Special Key"++
  - pymdownx.keys

  # 支持提示框的折叠
  # 不可折叠：!!!
  # 可折叠：???
  # 可折叠（默认打开）：???+
  - pymdownx.details

  # 文本高亮
  # 高亮：==Text==
  - pymdownx.mark

  # 文本下划线及上标
  # 下划线：^^Text^^
  # 上标：x^2^
  - pymdownx.caret

  # 文本删除线及下标
  # 删除线：~~Text~~
  # 下标：H~2~O
  - pymdownx.tilde

  # 数学表达式
  # 行内：$math$
  # 单独：$$math$$
  - pymdownx.arithmatex:
      generic: true

  # 斜体与粗体优化，更好的嵌套使用
  - pymdownx.betterem:
      smart_enable: all # 对斜体和粗体都生效

  # 文本评论
  # 增加：{++Text++}
  # 删除：{--Text--}
  # 高亮：{==Text==}
  # 注释：{>>Text<<}
  # 替换（用 2 替换 1）：{~~Text1~>Text2~~}
  - pymdownx.critic:
      mode: view # view 显示差异，accept 显示修改后，reject 显示修改前

  # 任务列表
  # 已勾选：- [X]
  # 未勾选：- [ ]
  - pymdownx.tasklist:
      custom_checkbox: true # 允许修改复选框样式（默认已修改）
      clickable_checkbox: true # 允许点击复选框

  # 代码高亮
  # 指定标题：```lang title="Text"
  # 不显行号：```lang linenums="0"
  # 指定起始行号：```lang linenums="2"
  # 指定高亮行号：```lang hl_lines="2-4"
  - pymdownx.highlight:
      use_pygments: true # 使用 Pygments 而不是 JavaScript 来渲染高亮
      linenums: true # 默认显示行号
      linenums_style: pymdownx-inline # 行号样式 pymdownx-inline 或者 inline 和 table
      anchor_linenums: true # 用锚链接包装代码行号，便于超链接和共享（就是行号可以像锚点一样被点击）
      line_spans: __span # 这对于高亮功能正常工作至关重要
      pygments_lang_class: true # 对于自定义注释标记的运行至关重要
      # auto_title: true # 自动为所有代码块添加一个标题

  - pymdownx.emoji: # Emoji 表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences: # 各种嵌套
      custom_fences:
        - name: mermaid # 允许 mermaid 图表语法
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed: # 标签块
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # 格式：
  # === "Tab 1"
  #     something
  # === "Tab 2"
  #     something

theme:
  name: material # 第三方主题名称
  custom_dir: docs/overrides # 覆盖部分原来的主题（重载目录）
  language: zh # material 语言
  features:
    # - header.autohide # 顶栏自动隐藏
    - content.tooltips # 提示框（以前有的样式变好看了，此外还支持更高级的提示框语法）
    - content.code.copy # 例如：``` python { .yaml .copy } 默认开启，{ .yaml .no-copy } 关闭
    - content.code.annotate # 允许内联代码注释
    - content.tabs.link # 同样的标签，整个网站的同步切换，如 C -> C++，则其它类似的全部标签都同步切换
    - content.action.edit # 允许页面被编辑（会出现编辑按钮）
    - content.action.view # 允许查看页面的源代码（会出现查看源代码按钮）
    - announce.dismiss # 公告栏可以被关闭
    # - navigation.expand # 左侧边栏节点默认全部展开（与 navigation.prune 不兼容）
    # - navigation.prune # 左侧栏节点至多展开一个，以此来减小站点的构建大小（对于页数100+的网站很有用，但是！与 navigation.expand 不兼容）
    - navigation.tabs # 页面顶部导航栏
    - navigation.footer # 页面底下换页的支持
    - navigation.indexes # 左侧边栏大节点是否可以被导向到 index.md
    - navigation.instant # 页面不会重复加载（已加载页面不会再次加载）
    - navigation.instant.progress # 加载速度慢时，在页面顶部显示加载进度（400ms 以上加载时间才会显示它）
    # - navigation.tabs.sticky # 导航栏标题栏位置固定
    # - navigation.sections # 左侧边栏节点是否保持展开
    - navigation.top # 回到顶部的按钮
    - navigation.tracking # 锚点跟踪
    - search.share # 搜索栏分享按钮
    - search.suggest # 搜索栏内容建议
    - search.highlight # 搜索栏内容高亮
    - toc.follow # 锚点关注，侧边栏自动滚动，使锚点总是可见
    # - toc.integrate # 右边侧栏是否集成到左侧边栏
  palette: # 界面整体样式
    - media: "(prefers-color-scheme)" # 系统主题
      toggle: # 切换按钮
        icon: material/theme-light-dark # 图标
        name: 切换至明亮主题 # 提示词
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      # primary: grey # 标题栏颜色（建议自定义 CSS 调整，因为 footer 不会被此参数影响！）
      accent: purple # 链接高亮颜色
      toggle:
        icon: material/weather-sunny
        name: 切换至暗黑主题
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: black
      # accent: yellow
      toggle:
        icon: material/weather-night
        name: 切换至系统主题
  font: false # 避免从谷歌加载字体导致网页加载变慢（具体参数可以在自定义 CSS 中指定）
  logo: logo.png # 页面左上角徽标
  favicon: logo.png # 网页的图标
  icon: # 图标重载，替换掉默认的图标
    previous: fontawesome/solid/angle-left # 左下角向前翻页的图标
    next: fontawesome/solid/angle-right # 右下角向后翻页的图标
    repo: fontawesome/brands/github # 右上角仓库图标
    edit: material/pencil # 页面编辑的图标
    view: material/eye # 页面查看源代码的图标
    # annotation: material/arrow-right-circle # 提示按钮的图标，详细操作见 https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-content-tabs-tab-1

extra: # 额外设定
  alternate:
    - name: 简体中文
      link: /
      lang: zh
    - name: English
      link: /
      lang: en
  homepage: . # 左上角徽标链接的地址
  annotate: # 允许代码块非注释内的提示，我也不太懂什么意思，貌似是可以在代码里面加悬浮提示框，而不只是在注释中（感觉这样不好，虽然我不用，但不能没有）
    json: [.s2]
  social: # 社交联系方式（页面右下角内容）
    - icon: fontawesome/brands/github
      link: https://github.com/Xiaokang2022/tkintertools/
      name: Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tkintertools/
      name: PyPI
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/498105668
      name: 哔哩哔哩
    - icon: fontawesome/solid/paper-plane
      link: mailto:2951256653@qq.com
      name: 联系作者
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie Consent / Cookie 许可
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      <br/>
      我们使用 cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们正在搜索的内容。在您的同意下，您将帮助我们改进我们的文档。

extra_javascript:
  - extra/javascript/shortcuts.js # 绑定左右键换页的键盘快捷键
  - extra/javascript/mouse.js # 鼠标点击烟花效果
  - extra/javascript/typing.js # 打字机效果
  # - extra/javascript/canvas-nest.js # 背景效果
  - extra/javascript/tongji.baidu.js # 百度统计脚本
  - extra/javascript/mathjax.js # 保证数学表达式能正确显示的运行时环境（下面的也是）
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra/css/extra.css # 加载自定义的样式
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css # 设置字体（霞鹜文楷）

plugins:
  - search: # built-in
      lang:
        - zh
        - en
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      locale: zh
      timezone: Asia/Shanghai
  # - git-authors: # 当配置不好下方的 git-committers 时可采用这个
  - git-committers:
      repository: Xiaokang2022/tkintertools
      branch: docs
      token: !ENV ["GH_TOKEN"] # 需要自行在终端中设置临时环境变量，强烈不建议显式地在此处设置 token
  - glightbox:
      background: none
  - statistics:
      codelines_per_minute: 10
      words_per_minute: 300
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

nav:
  - Home / 主页:
      - Homepage / 主页: index.md
      - License / 项目许可: LICENSE.md
      - Changelog / 更新日志: CHANGELOG.md
      - Todo / 待办事项: TODO.md
      - Contribution Guide / 贡献指南: CONTRIBUTING.md
      - Security Policy / 安全策略: SECURITY.md
      - Code of Conduct / 行为准则: CODE_OF_CONDUCT.md
      - Sponsor this Project / 赞助项目: Sponsor.md

  - Tutorials & Documents / 教程和文档: https://xiaokang2022.github.io/tkintertools-docs/

  - Projects / 项目:
      - Overview - 项目概览: projects/index.md
      - 1. Intelligent Magic Cube: projects/pages/1.md
      - 2. Chinese Chess: projects/pages/2.md
      - 3. Super Gobang: projects/pages/3.md
      - 4. Todo List: projects/pages/4.md
      - 5. Login2.0: projects/pages/5.md

  - Videos / 视频:
      - Overview - 视频概览: videos/index.md
      - 干掉 tkinter！tkintertools 大更新啦！: videos/pages/4.md
      - tkintertools 又更新啦！: videos/pages/3.md
      - 碾压 tkinter 的 UI 框架：tkintertools 3.0.0 正式进入 beta 公测阶段: videos/pages/2.md
      - 这还是你记忆中的 tkinter 的程序吗？？？: videos/pages/1.md

  - News / 新闻:
      - Series 3 / 系列 3:
          - 3.0.0(pre): news/3.0.0/News.md
      - Series 2 / 系列 2:
          - 2.6.21: news/2.6.21/News.md
          - 2.6.20: news/2.6.20/News.md
          - 2.6.19: news/2.6.19/News.md
          - 2.6.18: news/2.6.18/News.md
          - 2.6.17: news/2.6.17/News.md
          - 2.6.16: news/2.6.16/News.md
          - 2.6.15: news/2.6.15/News.md
          - 2.6.14: news/2.6.14/News.md
          - 2.6.13: news/2.6.13/News.md
          - 2.6.12: news/2.6.12/News.md
          - 2.6.11: news/2.6.11/News.md
          - 2.6.10: news/2.6.10/News.md
          - 2.6.9: news/2.6.9/News.md
          - 2.6.8: news/2.6.8/News.md
          - 2.6.7: news/2.6.7/News.md
          - 2.6.6: news/2.6.6/News.md
